version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
    environment:
      - EMAIL=email_receiver
      - TXSFILE=txns.csv
      - SENDEREMAIL=sender_email
      - SENDERPASSWORD=sender_email_password
    depends_on:
      - mongo
    command: >
      sh -c "sleep 5 && ./app $EMAIL $TXSFILE $SENDEREMAIL $SENDERPASSWORD"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
